/*  File generated by: Map Ed v0.99 */

#include "GBA_Types.h"


#define bgPaletteSize 256*2
extern const u16 bgPalette[256];
#define bgTilesSize 944*2
extern const u16 bgTiles[944];
#define bgLayer0Size 2048*2
extern const u16 bgMapLayer0[2048];
#define bgLayer1Size 2048*2
extern const u16 bgMapLayer1[2048];
